# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CriaNotesService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43riaNotesService.proto\x12\tcrianotes\"2\n\x0eNewNoteRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"/\n\x0bNoteRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07note_id\x18\x02 \x01(\t\"\x1e\n\x0bNoteContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"6\n\rMultipleNotes\x12%\n\x05notes\x18\x01 \x03(\x0b\x32\x16.crianotes.NoteContent\"\x17\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x19\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf9\x01\n\x10\x43riaNotesService\x12\x37\n\x07\x41\x64\x64Note\x12\x19.crianotes.NewNoteRequest\x1a\x11.crianotes.Status\x12\x37\n\nDeleteNote\x12\x16.crianotes.NoteRequest\x1a\x11.crianotes.Status\x12\x39\n\x07GetNote\x12\x16.crianotes.NoteRequest\x1a\x16.crianotes.NoteContent\x12\x38\n\x0bGetAllNotes\x12\x0f.crianotes.User\x1a\x18.crianotes.MultipleNotesB\x15Z\x13./craftyllamaprotosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CriaNotesService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023./craftyllamaprotos'
  _globals['_NEWNOTEREQUEST']._serialized_start=37
  _globals['_NEWNOTEREQUEST']._serialized_end=87
  _globals['_NOTEREQUEST']._serialized_start=89
  _globals['_NOTEREQUEST']._serialized_end=136
  _globals['_NOTECONTENT']._serialized_start=138
  _globals['_NOTECONTENT']._serialized_end=168
  _globals['_MULTIPLENOTES']._serialized_start=170
  _globals['_MULTIPLENOTES']._serialized_end=224
  _globals['_USER']._serialized_start=226
  _globals['_USER']._serialized_end=249
  _globals['_STATUS']._serialized_start=251
  _globals['_STATUS']._serialized_end=276
  _globals['_CRIANOTESSERVICE']._serialized_start=279
  _globals['_CRIANOTESSERVICE']._serialized_end=528
# @@protoc_insertion_point(module_scope)
